apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/component: log-collector
    app.kubernetes.io/part-of: efk
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
