apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/component: log-collector
    app.kubernetes.io/part-of: efk
automountServiceAccountToken: true
