apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app: elasticsearch
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: efk
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
