apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - namespace.yaml
  - elasticsearch/statefulset.yaml
  - elasticsearch/service-headless.yaml
  - elasticsearch/service-client.yaml
  - elasticsearch/pdb.yaml
  - fluentd/serviceaccount.yaml
  - fluentd/clusterrole.yaml
  - fluentd/clusterrolebinding.yaml
  - fluentd/daemonset.yaml
  - kibana/deployment.yaml
  - kibana/service.yaml
